

//This will Login page
to loginPage
	(*
	click imageName:"Login/loginButton", waitFor:20
	*)
	wait 5
	Click imageName:"Login/Login",waitFor:20
	wait 10
	Click imageName:"Login/emailInputFieldNew", waitFor:15
	wait  5
	TypeText "thatsdg63@gmail.com"
	wait 3
	TypeText tabKey
	Click imageName:"Login/passwordInputField", waitFor:15
	TypeText "Divy@nkg6784"
	Click imageName:"Login/loginButtonNewSmall", waitFor:20
	Click imageName:"Login/maximizeScreen", waitFor:10
	
	Click imageName:"Login/divyankTextProfileIconN", waitFor:20
	Click imageName:"Login/logoutButtonN"
	wait 5
	
	
end loginPage


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

//This will login with Google
to loginWithGoogle
	ScrollWheelDown 1
	wait 5
	Click imageName:"Login/loginWithGoogleSmall", waitFor:5
	Click imageName:"Login/emailInput", waitFor:5
	TypeText "divyankgupta143@gmail.com"
	wait 5
	Click imageName:"Login/nextButtonAfterEnterEmail", waitFor:3
	Click imageName:"Login/enteryourpasswordShowpassword", waitFor:3
	TypeText "Divy@nkg6784"
	wait 5
	Click imageName:"Login/checkboxShowpassword", waitFor:3
	Click imageName:"Login/nextButtonLogin", waitFor:3
	If ImageFound(imageName:"Login/divvyankTextBlack", waitFor:3) then
		Log "Successfully login"
		
	Else
		log "Failed account verification"
	End if
end loginWithGoogle















