//This will run Script ------------------------------------------------------

homepage.LaunchBrowser
homepage.fillContactForm
//loginPage.loginPage
// signuppage.registerUser


//Trying to delete cookies

set driverName to WebDriver(host:"192.168.0.96", browser: "msedge", name: "192.168.0.96")
log driverName
set the driverNmae's cookies to empty










(*
loginpage.loginWithGoogle
*)
(*basicUI.navigateAboutOption

loginPage.loginPage*)
(*
signUp.joinNowToPractice
*)
